### ISSUE TITLE
Possible values of the parameter(logformat) of LogLoader Class is not defined 

### ISSUE THREAD

**Issue by tamanna-sb** [afrin110203/LogAnomaliesDetectionDL#6]
<img width="443" alt="Screen Shot 2022-10-19 at 1 04 44 AM" src="https://user-images.githubusercontent.com/14105107/196620208-9da742aa-4b14-4d6d-bf61-34490037f780.png">

In _logloader.py_ file , _LogLoader_ Class takes _logformat_ as an argument. But the possible values of _logformat_ is not defined in README.md or as a comment or on documentation. This can be crucial for new contributors since their is no dummy or final code to initialize this class, new contributors cannot initialize the class and test the correctness of the implemented methods or adding methods for further causes. 

The program has no main function or class initialization code. Add Only some classes and functions are added. Kindly add more codes for testing the classes.

**Comment by RubyaAfrin** [comment]
Thank you for reporting this. I have already configured the _logformat_ variable and input-output file directory initialization.
 
<img width="497" alt="image" src="https://user-images.githubusercontent.com/7861918/197278396-3bd3a315-2d97-4edc-ab46-f7286f1ee245.png">

However, different log files have different format which was difficult to merge into one format. That's why, here I am using only the logformat of Apache log file.
