### ISSUE TITLE
Add documentation with information about the dataset 

### ISSUE THREAD

**Issue by tamanna-sb** [afrin110203/LogAnomaliesDetectionDL#7]
1. In dataset, only structure of apache logs are given. But other log files have different structures. Mention the structures of other log files too. 
2. Define which logs are anomaly
3. Define what each column means in _Apache_2k.log_structured.csv_; especially EventTemplate.
4. You can add those information in README.md

**Comment by RubyaAfrin** [comment]
Thank you for your valuable inquiry.

1. Primarily, I am planning to work on "Apache.log" dataset, that's why I have provided only "Apache_2k.log_structured.csv" file here.
2. In "Apache_2k.log_structured.csv" file, the column "Level" defines a message- "_error_" which is considered as anomaly.
3. The column "_EventTemplate_" is nothing but the a generalized form of log format input of "_Content_". We have replaced all the digits of "_content_" with "_<*>_" in order to have desired message content from the log file.
4. I will prepare a documentation file and link to README.md
